---
- block:
    - name: Install redis server
      apt:
        name: redis-server
        autoremove: true
        state: latest

    - name: Configure redis
      copy:
        src: redis.conf
        dest: "/etc/redis/redis.conf"
        owner: root
        group: root
        mode: 0644
        force: true
      notify: restart redis-server

    - name: Add user www-data to group redis
      user:
        name: "www-data"
        groups: redis

    - name: Start and enable redis
      systemd:
        name: redis
        state: started
        enabled: true

  become: yes
  become_user: root
