---
  - name: Deploy app from git (git clone)
    git: repo={{ repo }} dest={{ www_path }}/{{ app }}

  - name: Run composer install on app
    composer:
       command: install
       working_dir: "{{ www_path }}/{{ app }}"

  - name: Change folder permissions
    file: path={{ www_path }}/{{ app }}/{{ item }} mode=0777 recurse=yes
    with_items:
      - storage
      - bootstrap/cache
    become: yes
    become_user: root
