---
- block:
    - name: Install Webserver stack (nginx, php etc)
      apt: pkg={{ item }} state=present
      with_items:
        - nginx
        - php7.2
        - php7.2-common
        - php7.2-xml
        - php7.2-mbstring
        - php7.2-fpm
        - php7.2-curl
        - php7.2-cli
        - php7.2-json
        - php7.2-mysql
        - php7.2-pgsql
        - php7.2-zip
        - php7.2-gd
        - php7.2-bcmath

    - name: Check if composer is installed
      stat: "path=/usr/local/bin/composer"
      register: composer_bin

    - name: Download composer installer
      get_url:
         url: https://getcomposer.org/installer
         dest: /tmp/composer-installer.php
         mode: 0755
      when: not composer_bin.stat.exists

    - name: Run composer installer
      command: php /tmp/composer-installer.php --install-dir=/usr/local/bin --filename=composer
      when: not composer_bin.stat.exists

  become: yes
  become_user: root
