---
- name: Provision an Ubuntu 18.04 DNS Server (using dnsmasq)
  hosts: all
  vars:
    ansible_python_interpreter: /usr/bin/python3
    
  roles:
     - role: dnsmasq
       vars:
        dnsmasq_static_addresses:
        - address: '192.168.1.10'
          name: 'provisioner.com'


#   1) Edit your hosts file
#   2) Edit this file an put in the right values for the various vars 
#   3) Run: ansible-playbook file_and_dns_server.yml -i hosts --ask-become-pass (--ask-pass is only needed if your hosts are remote)