---
- name: Provision an Ubuntu 18.04 File Server
  hosts: all
  vars:
    ansible_python_interpreter: /usr/bin/python3
    www_path: '{{ansible_env.HOME}}/www/'
    app: 'file_server'

  pre_tasks:
    - name: Create file server base directory (for nginx)
      file: path='{{ansible_env.HOME}}/www/{{app}}' state=directory

  roles:
     - common
     - nginx_and_php
     - role: configurations
       vars:
        is_not_laravel: ''


#   1) Edit your hosts file
#   2) Edit this file an put in the right values for the various vars 
#   3) Run: ansible-playbook file_and_dns_server.yml -i hosts --ask-become-pass (--ask-pass is only needed if your hosts are remote)