---
- name: Provision an Ubuntu 18.04 Web Application Server
  hosts: all
  vars:
    ansible_python_interpreter: /usr/bin/python3
    www_path: {{ansible_env.HOME}}www/
    app: 'provisioner_backend'
  roles:
     - common
     - nginx_and_php
     - role: postgres
       become: yes
       vars:
        postgresql_databases:
          - name: phc20xx
     - role: deploy
       vars:
        repo: 'https://github.com/amestsantim/provisioner_backend.git'
     - configurations
     - redis


#   1) Edit your hosts file
#   2) Edit this file an put in the right values for the various vars 
# 	3) Run: ansible-playbook web_and_db_server.yml -i hosts --ask-become-pass