---
- name: Provision an Ubuntu Web Application and Database Server
  hosts: all
  vars:
    ansible_python_interpreter: /usr/bin/python3
    www_path: '{{ansible_env.HOME}}/www/'
    app: 'provisioner_backend'
  roles:
     - common
     - nginx_and_php
     - role: geerlingguy.postgresql
       become: yes
       vars_files:
        - vars/main.yml
     - role: deploy
       vars:
        repo: 'https://github.com/amestsantim/provisioner_backend.git'
     - configurations
     - https


#   1) Edit your hosts file
#   2) Edit this file an put in the right values for the various vars 
#   3) Run: ansible-playbook web_and_db_server.yml -i hosts --ask-become-pass (--ask-pass is only needed if your hosts are remote)