postgresql_databases:
  - name: '{{app}}'
postgresql_users:
  - name: postgres
    password: postgres
    encrypted: true
# postgresql_data_dir: "{{ansible_env.HOME}}/postgresql/{{ __postgresql_version }}/main"