---
  - name: Clone the repo into the home dir
    git: repo=https://github.com/nicolasff/webdis dest='{{ ansible_env.HOME }}/webdis'
    
  - name: Make sure build-essential and libevent-dev are installed
    apt:
      name: build-essential, libevent-dev
      state: present
    become: yes

  - name: make clean all
    make:
      chdir: '{{ ansible_env.HOME }}/webdis'
      target: all

  - name: Move webdis to the usr/share directory
    copy:
      remote_src: yes
      src: '{{ ansible_env.HOME }}/webdis'
      dest: /usr/share/
    become: yes

  - name: Recursively remove directory
    file:
      path: '{{ ansible_env.HOME }}/webdis'
      state: absent

  - name: Copy systemd unit file
    template:
      src: webdis.service
      dest: /etc/systemd/system/webdis.service
    become: yes

  - name: Enable the webdis service
    systemd:
      daemon_reload: yes
      name: webdis.service
      enabled: yes
      state: started
    become: yes