
galaxy_info:
  author: Trainline SAS
  description: "Install, configure and manage PostgreSQL clusters"
  license: MIT

  min_ansible_version: 2.5

  platforms:
  - name: Ubuntu
    versions:
      - xenial
  - name: Debian
    versions:
      - jessie
      - stretch
      - buster

  galaxy_tags: ['postgresql', 'cluster', 'ha', 'database', 'replication']

dependencies: []
