- name: Test if the PostgreSQL server is up
  become: true
  become_user: postgres
  become_method: "{{ postgres_become_method }}"
  command: psql --port={{ postgres_port }} --command='select NOW()'
  register: postgres_up
  ignore_errors: yes
  check_mode: no
  changed_when: false

- name: "Install required packages for 'postgres_user' ansible module"
  apt:
    name:
      - libpq-dev
      - python-psycopg2

- name: Create PostgreSQL user
  become: true
  become_user: postgres
  become_method: "{{ postgres_become_method }}"
  postgresql_user:
    port:             "{{ postgres_port }}"
    name:             "{{ postgres_username }}"
    password:         "{{ postgres_password }}"
    encrypted:        true
    role_attr_flags:  "{{ postgres_permissions }}"
  when:
    - postgres_up.rc == 0
