- name: Add Postgres repository key
  apt_key: id=7FCC7D46ACCC4CF8 url=https://apt.postgresql.org/pub/repos/apt/ACCC4CF8.asc state=present
  when: ansible_distribution_release != 'NA'

- name: Add Postgres repository
  apt_repository: repo="deb http://apt.postgresql.org/pub/repos/apt/ {{ ansible_distribution_release }}-pgdg main"
  when: ansible_distribution_release != 'NA'

- name: Increase shmmax sysctl paramater
  sysctl: name="kernel.shmmax" value=586162176 sysctl_set=yes state=present reload=yes

- name: Install rsync
  apt: name=rsync
  when: ansible_distribution_release != 'NA'

- name: Install time
  apt: name=time state=present

- name: Install barman-cli
  apt: name=barman-cli state=present

- name: Install pg-activity
  apt: name=pg-activity state=present
