---
- block:
    - name: "Update cache"
      apt: update_cache=yes

    - name: Install common apps
      apt: pkg={{ item }} state=present
      with_items:
        - git
        - vim
        - supervisor

  become: yes
  become_user: root
