---
- block:
    - name: "Update cache"
      apt: update_cache=yes
      ignore_errors: yes

    - name: Install java sdk
      package: 
        state: present
        name:
          - openjdk-8-jdk

    - name: Download latest geoserver (v2.17.x)
      get_url:
        url: https://build.geoserver.org/geoserver/2.17.x/geoserver-2.17.x-latest-bin.zip
        dest: '{www_path}/geoserver-2.17.x-latest-bin.zip'
        mode: '0770'

    - name: Add the 'geoserver' user
      user:
        name: geoserver
        group: geoserver

    - name: Extract geoserver
      unarchive:
        src: '{www_path}/geoserver-2.17.x-latest-bin.zip'
        dest: '{www_path}/geoserver'
        remote_src: yes
        mode: '0664'
        group: geoserver

    - name: Copy systemd unit file
      template:
        src: geoserver.service.j2
        dest: /etc/systemd/system/geoserver.service
      become: yes

    - name: Enable the geoserver service
      systemd:
        daemon_reload: yes
        name: geoserver.service
        enabled: yes
        state: started

  become: yes
  become_user: root
